### ISSUE TITLE
Multiple issues with the 1.9 bundle

### ISSUE THREAD

**Issue by dparv** [canonical/bundle-kubeflow#1007]
### Bug Description

```
dex-auth/0*                   waiting   idle   10.244.2.6                  List of <ops.model.Relation oidc-client:66> versions not found for apps: oidc-gatekeeper
istio-pilot/0*                waiting   idle   10.244.0.23                 Execution handled 2 errors.  See logs for details.
katib-controller/0*           blocked   idle   10.244.2.9                  [k8s-service-info] Missing relation with a k8s service info provider. Please add the missing relation.
oidc-gatekeeper/0*            blocked   idle   10.244.0.34                 Missing relation with a Dex OIDC config provider. Please add the missing relation.
```

### To Reproduce

juju deploy kubeflow --channel 1.9/stable

### Environment

Juju 3.6/beta
AKS 1.28.10

### Relevant Log Output

```shell
dex-auth
 - juju: https://pastebin.canonical.com/p/Phm3zWhRpd/
 - k8s: https://pastebin.canonical.com/p/Jby6Smr4qN/ and https://pastebin.canonical.com/p/h2K3szwZmp/
istio-pilot
 - juju: https://pastebin.canonical.com/p/xBVJM3G97J/
 - k8s: https://pastebin.canonical.com/p/43ntzxRSKz/
katib-controller
 - juju: https://pastebin.canonical.com/p/2Xq2XgWvj3/
 - k8s: https://pastebin.canonical.com/p/yDZ4Mcx7pn/ and https://pastebin.canonical.com/p/9dxRBjNZbV/
oidc-gatekeeper
 - juju: https://pastebin.canonical.com/p/8BfQCzvHps/
 - k8s: https://pastebin.canonical.com/p/dfCfSZN9N9/ and https://pastebin.canonical.com/p/KGjwDX66gm/
```

**Comment by kimwnasptd** [comment]
@dparv I think a lot of those are because of missing relations. I tried to deploy 1.9 (in MicroK9s) from the [stable bundle](https://github.com/canonical/bundle-kubeflow/blob/main/releases/1.9/stable/bundle.yaml) today and didn't see these

I think the above relations are missing, or you need to double check:
- https://github.com/canonical/bundle-kubeflow/blob/main/releases/1.9/stable/bundle.yaml#L280-L281
- https://github.com/canonical/bundle-kubeflow/blob/main/releases/1.9/stable/bundle.yaml#L294

Regarding the issue with Istio, we'll need a dedicated bug. I had seen this and this should have been tracked in https://github.com/canonical/bundle-kubeflow/issues/1006, but the issue was not clearly exposed in this issue so it was missed. I'll make sure we track it in a dedicated one.

**Comment by DnPlas** [comment]
Hey @dparv, a couple notes:

* `katib-controller` - The unit is Blocked because of a missing relation (`[k8s-service-info] Missing relation with a k8s service info provider. Please add the missing relation.`). For most charms, when units go to BlockedStatus, the recommended action for the user will appear in the status message. To resolve this, please add the relation `juju integrate katib-db-manager:k8s-service-info katib-controller:k8s-service-info`.

* `oidc-gatekeeper` - This is the same situation as the one before, but with a different relation. To resolve this, please add the relation `juju integrate oidc-gatekeeper:dex-oidc-config dex-auth:dex-oidc-config`

NOTE: if you are following the [upgrade guide](https://charmed-kubeflow.io/docs/upgrade-18-19) from 1.8 to 1.9, make sure you run all the steps, including the ones at the bottom that say "adding new relations".

* `dex-auth` - It is waiting for the `oidc-gatekeeper` charm to share its data through the `oidc-client` relation (a different one from above), this should go away when `oidc-gatekeeper` is active and idle, as this is a limitation of the SDI library we use.

* `istio-pilot` - This error is caused because the Istio Gateway Service is not correctly configured. By default, the `istio-operators` will assume you have a LoadBalancer configured in your cluster, and will fail like this if that is not the case. To resolve it, please configure `istio-ingressgateway` using the `gateway_service_type` config option to match your cluster's configuration. For example, if you have a LoadBalancer, you can leave it as is, just ensure you have a LoadBalancer correctly configured, if you are trying to use a ClusterIP, then you can do something like `juju config istio-ingressgateway gateway_service_type=ClusterIP`.

**Comment by DnPlas** [comment]
@dparv could you also please confirm how you deployed the CKF bundle? We want to make sure those missing relations are in place.

**Comment by DnPlas** [comment]
@dparv thanks for confirming. Please use [this bundle definition](https://github.com/canonical/bundle-kubeflow/blob/main/releases/1.9/stable/bundle.yaml) as reference, as it changed quite a few things.

After that, please let us know if the error persists; otherwise I think we can close the issue.

**Comment by DnPlas** [comment]
After syncing with @dparv, this issue can be closed for now. Feel free to re-open if the issue persists after the recommended solutions from above.
