### ISSUE TITLE
[docs] Clarify step 6.: Set URL in authentication methods

### ISSUE THREAD

**Issue by phvalguima** [canonical/bundle-kubeflow#392]
Hi,

Following the documentation on charmed-kubeflow, I get up until step 6. from: https://charmed-kubeflow.io/docs/install

``` A final step to enable your Kubeflow dashboard access is to provide your dashboard public URL ```

If I set the URL from kubeflow-dashboard, I will get the following error:

```
time="2021-09-07T20:16:06Z" level=error msg="OIDC provider setup failed, retrying in 10 seconds: oidc: failed to decode provider discovery object: expected Content-Type = application/json, got \"text/html; charset=UTF-8\": invalid character '<' looking for beginning of value"
```

These services are waiting for a json format and are receiving an html instead.

The correct setup is to have URL described in Step 6. as istio-ingressgateway's public URL instead of kubeflow-dashboard's.

**Comment by DomFleischmann** [comment]
I agree that this seems a bit confusing. @evilnick what are your thoughts?

**Comment by ca-scribner** [comment]
Summarizing some comments from chat:

@ca-scribner: It feels like to follow our current instructions you need to know a lot about kubeflow/how we deploy it (for example, knowing either which deployment provides the central dashboard UI, or that we wire that up to the istio-ingressgateway).  I like updating to something like: `Where <URL> is the hostname that the Kubeflow dashboard responds to.  For example, in a typical installation the Kubeflow dashboard is deployed as XXX and its IP can be found by executing kubectl get svc istio-ingressgateway -o json | jq ".spec.clusterIP"`

@DomFleischmann: I don't really like the idea of adding complex bash commands without much explanation

@knkski:  think the existing explanation is fine since it mentions the 10.64.140.43.nip.io address, which most people that aren't advanced users will use.  and then if we added a note like "if you're an advanced user, run kubectl get svc ... to find the IP that you should use", that would cover pretty much everybody

@ca-scribner: I like keeping it simple and deferring to microk8s conventions, but as written I don't think it is easy for someone new to navigate.  The first time I tried this I had to reverse engineer the `microk8s enable kubeflow` command to figure out what IP we were looking for.  I don't know exactly what should be here, but I think it should be something ready for copy/paste since the doc is supposed to be a basic install guide.  I like mentioning context on why we do what we do, but we also need to include batteries

**Comment by DomFleischmann** [comment]
The documentation has been updated and should be more clear now.
