### ISSUE TITLE
HTTP ERROR 403 Kubeflow dashboard juju ks3

### ISSUE THREAD

**Issue by pdavis39** [canonical/bundle-kubeflow#402]
We have an environment that works and other Kubernetes pods running without issues.  

This environment is K3S, Ubuntu 18.04 versus microk8s.

When we use chrome, safari, or firefox we get the same error  HTTP ERROR 403.  Dex does not appear to be able to route us to the login screen

The curl error message gives us the most useful info

HTTP/1.1 403 Forbidden
< date: Tue, 26 Oct 2021 13:20:08 GMT
< server: istio-envoy
< content-length: 0
 
Any suggestions on how to resolve this issue?  Our current thought is this is a Dex issue

Thanks in advance for your help

Paul

**Comment by DnPlas** [comment]
Hi @pdavis39, thanks for reporting this. It seems to me this issue is similar to #403, but as per @banderlog's [comment](https://github.com/canonical/bundle-kubeflow/issues/388#issuecomment-955682733) it does not happen anymore. If you still have the issue, do you mind sharing details like `kubectl logs pod/dex-auth-<suffix> -n kubeflow`, `kubectl get configmap/dex-auth-config-config -n kubeflow -o yaml` and the steps you are taking to deploy Kubeflow? Details about your setup will also be useful.

**Comment by pdavis39** [comment]
I found this issues resolved the problem https://issueexplorer.com/issue/canonical/bundle-kubeflow/383 

My guess is the linking between dec-auth and the iidc-gatekeeper was not initially set.
