### ISSUE TITLE
Kubeflow error activation

### ISSUE THREAD

**Issue by Pisou** [canonical/bundle-kubeflow#417]
#microk8s enable kubeflow --bundle=cs:kubeflow

Enabling dns...
Enabling storage...
Enabling ingress...
Enabling metallb:10.64.140.43-10.64.140.49...
Waiting for other addons to finish initializing...
Addon setup complete. Checking connectivity.

#Couldn't contact api.jujucharms.com from within the Kubernetes cluster
#Please check your network connectivity before enabling Kubeflow.

**Comment by DnPlas** [comment]
Hi @Pisou, seems like you are having a transient and/or a config issue with Microk8s. We recommend you deploy Charmed Kubeflow v1.4 following the steps in [this guide](https://charmed-kubeflow.io/docs/install) instead of enabling the add-on. Do you mind trying that?
Closing this issue as Charmed Kubeflow v1.4 is out and should be deployed as previously stated, feel free to re-open this or file a new issue in case you have any problems.
