### ISSUE TITLE
The mlpipeline-minio-artifact contains the value in open text in annotation

### ISSUE THREAD

**Issue by Barteus** [canonical/bundle-kubeflow#446]
Use kubectl to get the annotations, there is a full value.
```
$ kubectl describe secret mlpipeline-minio-artifact -n admin
Name:         mlpipeline-minio-artifact
Namespace:    admin
Labels:       controller-uid=<UUID>
Annotations:  metacontroller.k8s.io/last-applied-configuration:
                {"apiVersion":"v1","data":{"accesskey":"<base64value>","secretkey":"<base64value>...

Type:  Opaque

Data
====
accesskey:  20 bytes
secretkey:  88 bytes
```

This makes people who have only access to "describe secret" to see the values of it.

**Comment by ca-scribner** [comment]
(from jira) 
I believe this artifact is created by the kubeflow-pipelines-profile-controller charm via the sync.py script ([kfp-operators/sync.py at master · canonical/kfp-operators](https://github.com/canonical/kfp-operators/blob/master/charms/kfp-profile-controller/files/upstream/sync.py) ) that we’ve modified from upstream.  That sync.py file essentially defines yaml for objects that each kfp-enabled namespace should have, and I would have expected it to be what defined this object and annotation but I don’t see the code for that.

**Comment by ca-scribner** [comment]
This is starting to feel like a "can't fix", or at least not easily.  Some background is [here](https://github.com/kubernetes/kubernetes/issues/29923).  The tl/dr from that is:

> "Metadata is not treated as less confidential than main object content"

@natalian98 is looking into whether newer versions of metacontroller address this somehow but I'm not hopeful.

**Comment by natalian98** [comment]
Having tested the rbac model as suggested by metacontroller contributors, it looks that a role with `describe` access only doesn't work - it can be created, but will not grant any kind of access.
If a role with `get` access-only is created, the secret can be described as well.
As having read access with `get` enables to get the secret contents in yaml and use `edit` (without permission to actually patch the resource, but it can still be viewed), the annotation shouldn't be considered as a security issue. Therefore we also don't need to use `create` instead of `apply`.
