### ISSUE TITLE
Kubeflow UI not responding and dex-auth ERROR

### ISSUE THREAD

**Issue by psakamoori** [canonical/bundle-kubeflow#461]
As suggested in https://github.com/canonical/bundle-kubeflow/issues/450 - Creating new Issue ticket for below 

Not able to create Notebook Server

![Screenshot from 2022-06-03 00-31-34](https://user-images.githubusercontent.com/2974647/172215397-a4dc439e-3b75-40b8-95ee-48861b70fbf7.png)

dex-auth ERROR:
![Screenshot from 2022-06-03 10-34-09](https://user-images.githubusercontent.com/2974647/172215459-5b8ccccd-835b-4621-9909-c2f12570ebdd.png)

![Screenshot from 2022-06-03 10-37-56](https://user-images.githubusercontent.com/2974647/172215529-1f6f3994-a8e0-49a1-ab5e-e69e96f031e4.png)

![Screenshot from 2022-06-03 10-38-17](https://user-images.githubusercontent.com/2974647/172215559-d5cab03c-1ab9-4f15-ac7b-4e10b67465cb.png)

Appreciate any help on how to fix these issues...

Config settings:

$ microk8s kubectl patch role -n kubeflow istio-ingressgateway-operator -p '{"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"name":"istio-ingressgateway-operator"},"rules":[{"apiGroups":[""],"resources":[""],"verbs":["*"]}]}'
role.rbac.authorization.k8s.io/istio-ingressgateway-operator patched

$juju config dex-auth public-url=http://10.152.183.120.nip.io
$juju config oidc-gatekeeper public-url=http://10.152.183.120.nip.io

**Comment by psakamoori** [comment]
@natalian98  Please find the details below

snap info microk8s
==============

tacking = 1.21/stable

![Screenshot from 2022-06-07 13-45-07](https://user-images.githubusercontent.com/2974647/172479849-3e2bb9a2-ed35-4bfc-8e61-d59ec0981ff6.png)

microk8s status
============
![Screenshot from 2022-06-07 13-45-34](https://user-images.githubusercontent.com/2974647/172480030-bf0558ad-e28c-430f-b082-6bb577f4c5eb.png)

kubectl get svc -A | grep istio
======================

**External IP not assigned**

![Screenshot from 2022-06-07 13-49-09](https://user-images.githubusercontent.com/2974647/172480122-6ef7bba1-e873-43c2-ab1d-dad355f234a0.png)

![Screenshot from 2022-06-07 13-51-52](https://user-images.githubusercontent.com/2974647/172480213-e0a035d2-dead-4383-aef7-86cc5ca25ef4.png)

**Comment by natalian98** [comment]
From the `microk8s status` output I can see that metallb wasn't enabled, which is why the istio service's external ip is pending.

Try running `microk8s enable metallb:10.64.140.43-10.64.140.49` and the loadbalancer should get it assigned, allowing you to configure and access the dashboard using the `nip.io` link.

If problems persist, please attach juju logs. They can be retrieved using `juju debug-log --replay`.

**Comment by ca-scribner** [comment]
Regarding the problem accessing the notebook creation page (the first screenshot), I think this will be resolved if we get the regular access through the gateway figured out.  This looks familiar, although I can't remember exactly how to reproduce it.  I think it has to do with accessing the dashboard directly instead of through the gateway (I think coming in through the gateway attaches a user identity to the dashboard access, and without that things don't work right)

**Comment by ca-scribner** [comment]
I think this should be sorted out with the `metalb` fix, so I am closing this issue.  Please reopen though if it is still relevant.  Thanks!
