### ISSUE TITLE
tensorboard-controller issue KF-1.6

### ISSUE THREAD

**Issue by aym-frikha** [canonical/bundle-kubeflow#488]
Hello,

Trying to deploy charmed KF 1.6 beta on microk8s 1.22. I had an issue with tensorboard-controller wich is stuck on "Waiting for gateway relation".
Here is the [logs](https://pastebin.canonical.com/p/JrtYBXyJmn/) for the unit.

**Comment by DnPlas** [comment]
Hi @aym-frikha that is a known issue that has to do with how istio-pilot manages the `gateway-relation`. We have a [fix](https://github.com/canonical/istio-operators/pull/111) already merged in the 1.6 track and you should be able to see that message disappear if you deploy any Charmed Kubeflow with istio-pilot rev above 126.
This issue will be fixed by the 1.6/stable release.

**Comment by ca-scribner** [comment]
This is still sometimes an issue.  For mitigation steps, see the *Kubeflow Dashboard can’t be accessed* section of [this quickstart guide](https://charmed-kubeflow.io/docs/quickstart)

**Comment by ca-scribner** [comment]
Progress on this issue is tracked in canonical/istio-operators#113

**Comment by ShathishWarmaS** [comment]
tensorboard-controller                            waiting      1  tensorboard-controller   1.7/stable      156                  no       Waiting for gateway info relation

Please open the issue
