### ISSUE TITLE
User namespace is removed after upgrade from 1.6 to 1.7

### ISSUE THREAD

**Issue by i-chvets** [canonical/bundle-kubeflow#547]
User namespace is removed after upgrade from 1.6 to 1.7

admin space was created and some experiments were executed successfully with models and experiments stored in MLflow.

After the upgrade kubectl reports that admin namespace does not exist.

[Jira](https://warthogs.atlassian.net/browse/KF-1100)

**Comment by i-chvets** [comment]
During the upgrade the following relations could not be removed:
```
Relation provider              Requirer                       Interface      Type     Message
istio-pilot:ingress            dex-auth:ingress               ingress        regular  
istio-pilot:ingress            jupyter-ui:ingress             ingress        regular  
istio-pilot:ingress            katib-ui:ingress               ingress        regular  
istio-pilot:ingress            kubeflow-dashboard:ingress     ingress        regular  
istio-pilot:ingress            kubeflow-volumes:ingress       ingress        regular  
oidc-gatekeeper:client-secret  oidc-gatekeeper:client-secret  client-secret  peer
```

**Comment by i-chvets** [comment]
Interesting observation: upgrading just kubeflow-profiles does not drop user namespace.
Pre-upgrade:

```
$ microk8s.kubectl -n admin get all
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/ml-pipeline-visualizationserver-665bb6b8fc-7cqc5   2/2     Running   0          110m
pod/ml-pipeline-ui-artifact-5cfb68f5b7-d6drz           2/2     Running   0          110m
pod/test-0                                             2/2     Running   0          21m

NAME                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/ml-pipeline-visualizationserver   ClusterIP   10.152.183.123   <none>        8888/TCP   111m
service/ml-pipeline-ui-artifact           ClusterIP   10.152.183.226   <none>        80/TCP     110m
service/test                              ClusterIP   10.152.183.236   <none>        80/TCP     21m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ml-pipeline-visualizationserver   1/1     1            1           111m
deployment.apps/ml-pipeline-ui-artifact           1/1     1            1           111m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/ml-pipeline-visualizationserver-665bb6b8fc   1         1         1       111m
replicaset.apps/ml-pipeline-ui-artifact-5cfb68f5b7           1         1         1       111m

NAME                    READY   AGE
statefulset.apps/test   1/1     21m
```

Upgarde:

```
$ juju refresh kubeflow-profiles --channel latest/edge
Added charm-hub charm "kubeflow-profiles", revision 238 in channel latest/edge, to the model
Leaving endpoint in "alpha": kubeflow-profiles
```

Post-upgrade:

```
$ microk8s.kubectl -n admin get all
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/ml-pipeline-visualizationserver-665bb6b8fc-7cqc5   2/2     Running   0          111m
pod/ml-pipeline-ui-artifact-5cfb68f5b7-d6drz           2/2     Running   0          111m
pod/test-0                                             2/2     Running   0          22m

NAME                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
service/ml-pipeline-visualizationserver   ClusterIP   10.152.183.123   <none>        8888/TCP   111m
service/ml-pipeline-ui-artifact           ClusterIP   10.152.183.226   <none>        80/TCP     111m
service/test                              ClusterIP   10.152.183.236   <none>        80/TCP     22m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ml-pipeline-visualizationserver   1/1     1            1           111m
deployment.apps/ml-pipeline-ui-artifact           1/1     1            1           111m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/ml-pipeline-visualizationserver-665bb6b8fc   1         1         1       111m
replicaset.apps/ml-pipeline-ui-artifact-5cfb68f5b7           1         1         1       111m

NAME                    READY   AGE
statefulset.apps/test   1/1     22m
```

**Comment by i-chvets** [comment]
Looks like after refreshing kubeflow-dashboard use namespace disappears.

**Comment by DnPlas** [comment]
I am able to reproduce this issue, as you said, after refreshing `kubeflow-dashboard`, the behaviour is observed. Let's dig deeper in the following days to see if we are able to workaround this.

**Comment by ca-scribner** [comment]
## Summary

This is caused when refreshing the kubeflow dashboard charm because:
* kubeflow-dashboard charm <=1.6 creates the `admin` `Profile` at charm deploy [here](https://github.com/canonical/kubeflow-dashboard-operator/blob/1995114bc12c09cd87c1ec32369d92a26c23c947/src/charm.py#L140) (the name of this profile can be configured [here](https://github.com/canonical/kubeflow-dashboard-operator/blob/1995114bc12c09cd87c1ec32369d92a26c23c947/config.yaml#L11)).  
* kubeflow-dashboard 1.7 has removed this feature

No other Profile objects are affected, just the one that was generated by the dashboard charm

Because this `Profile` resource is deployed via podspec, it is also annotated with Juju annotations like:

```yaml
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
 annotations:
   controller.juju.is/id: 08053106-94d6-45df-811c-e698821aee01   # <---------This
   model.juju.is/id: f7e76919-0b19-47cc-8eb0-325dd06f807f          # <---------This
 creationTimestamp: "2023-03-10T19:09:45Z"
 finalizers:
 - profile-finalizer
 generation: 2
 labels:
   app.juju.is/created-by: kubeflow-profiles
   app.kubernetes.io/managed-by: juju                                             # <---------This
   app.kubernetes.io/name: kubeflow-dashboard                             # <---------This
   model.juju.is/name: kubeflow                                                        # <---------This
 name: admin
 resourceVersion: "98835"
 uid: 728f7f65-9953-494a-a93e-1dc4e7e8d9ce
spec:
 owner:
   kind: User
   name: admin
```

This means that Juju will clean up this object whenever the kubeflow-dashboard charm is removed, including when we refresh from dashboard 1.6 to 1.7.  

In past when upgrading from one podspec charm to another (say 1.4 to 1.6), Juju wouldn't touch the `Profile` object because it knew nothing about it changed.   That's why we didn't notice this happening in the past.  

## Actions we need for 1.6 -> 1.7

1. We should add to the guide a warning that the default `Profile` created by dashboard (`admin`, or whatever they named it via charm config) will be removed during the refresh.  

2. If the users want to keep this `admin` `Profile`, they can:
* `kubectl edit profile admin` (or whatever profile name they have)
* delete the 5 above marked annotations and labels on the `admin` `Profile` [^1]
This will also mean Juju is not directly managing that `Profile` (so it wouldn't try to clean it up if the model was removed), but that is ok since this object is an instance of a CRD that Juju **does** manage.  When Juju tries to delete the `Profile` CRD, our default profile will get cleaned up automatically by kubernetes.

## Todo:

* [ ] Someone else should test (2) above make sure I'm not mistaken.  I tried it a few times so I'm fairly confident, but just in case.  
* [ ] Add the above guidance to the upgrade docs.  

[^1]: Technically, I think they only need to remove the labels.  Opened up [this conversation](https://chat.charmhub.io/charmhub/pl/pfqmbtrygbbgbrmk85ba9zcj1h) to discuss further.  But for now, deleting everything seems to work well.

**Comment by ca-scribner** [comment]
Great suggestion from @i-chvets, we can directly instruct users on how to edit this.  Users can run the following:

With `kubectl` installed and a `.kube/config` set up for your cluster, updated `PROFILE_NAME` to match your default profile and execute the following to remove the annotations and labels:
```sh
PROFILE_NAME=admin

kubectl annotate profile $PROFILE_NAME controller.juju.is/id-
kubectl annotate profile $PROFILE_NAME model.juju.is/id-

kubectl label profile $PROFILE_NAME app.juju.is/created-by-
kubectl label profile $PROFILE_NAME app.kubernetes.io/managed-by-
kubectl label profile $PROFILE_NAME app.kubernetes.io/name-
kubectl label profile $PROFILE_NAME model.juju.is/name-
```

**Comment by DnPlas** [comment]
I think it is fair to have the [workaround](https://github.com/canonical/bundle-kubeflow/issues/547#issuecomment-1464393516) in the upgrade guide.

**Comment by i-chvets** [comment]
This workaround is acceptable. Will update the guide when I test this.

**Comment by i-chvets** [comment]
Is default profile always named `admin` in case of 1.6?

**Comment by i-chvets** [comment]
Just ran through instructions and `admin` namespace is still gone.

**Comment by i-chvets** [comment]
Followed update [1.6->1.7 upgrade guilde](https://github.com/canonical/bundle-kubeflow/blob/kf-1089-doc-upgrade-guide-1.6-1.7/docs/upgrade-guide-1.6-to-1.7.md) which has above workaround.
Observed `admin` namespace preserved.

**Comment by i-chvets** [comment]
Updated [1.6->1.7 upgrade guilde](https://github.com/canonical/bundle-kubeflow/blob/kf-1089-doc-upgrade-guide-1.6-1.7/docs/upgrade-guide-1.6-to-1.7.md)

**Comment by i-chvets** [comment]
Completed to-do items. Closing.
