### ISSUE TITLE
Multiple profiles are not visible

### ISSUE THREAD

**Issue by nishant-dash** [canonical/bundle-kubeflow#577]
Hello,

Continuing the discussion with @i-chvets , We have encountered an issue with multiple profiles not being visible in the kubeflow dashboard. 

The steps taken to create the profiles were 
- created profile
- authorizationpoilicy
- rolebinding for user

**Comment by ca-scribner** [comment]
I haven't recreated, but creating the `Profile` object should create profiles (if configured correctly).  An admin should not have to create AuthorizationPolicy or RoleBinding manually I dont think, this should be done by the profile controller.

I wonder if the `Profile` may have been misconfigured.  I think [this upstream doc](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#manual-profile-creation) would cover the manual use case.  The easiest way to share a Profile is through the Manage Contributors part of the UI, so that might be helpful.

**Comment by kimwnasptd** [comment]
Hey @nishant-dash, as @ca-scribner mentioned, creating Profile should result in the CentralDashboard showing that in the namespace dropdown. 

I'd like to try to reproduce this one though. @nishant-dash could you provide some more details on the above steps? I.e.
* Created the profile (how? Did you follow a specific guide? Did you deviate in any way from it?)
* AuthorizationPolicy (what AuthorizationPolicy did you create?)
* RoleBinding (what RoleBinding did you create?)
