### ISSUE TITLE
Standardize the ROCKs tags we use

### ISSUE THREAD

**Issue by kimwnasptd** [canonical/bundle-kubeflow#747]
### What needs to get done

Update our common action, if agreed, to build and publish rocks with a more readable image tag.
https://github.com/canonical/charmed-kubeflow-workflows/blob/main/.github/workflows/build_and_publish_rock.yaml

My proposal is that this tag should just be `<upstream-version>-<commit>`. 
I.e. `docker.io/charmedkubeflow/mlserver-mlflow:1.2.0-a3sd23`

### Why it needs to get done

Right now we are using different tags in some repos, that we used to build/publish images manually, and different in others. Here are some prime examples:
- `docker.io/charmedkubeflow/mlserver-mlflow:1.2.0_22.04_1`
  https://github.com/canonical/seldon-core-operator/blob/a557cbb3cc425c9ad28e3f4e8f3497bb0e325dfa/src/default-custom-images.json#L9C42-L9C97
- `charmedkubeflow/jupyter-scipy:v1.7.0-20.04-1_ad4e002`
  https://github.com/canonical/notebook-operators/blob/9b689afc6883b3f827cdf3b38df9cc68c1b1ce9d/charms/jupyter-ui/config.yaml#L25C9-L25C61

My main issue with the above are the use of the ubuntu version and the `_1` at the end. IMO both of those introduce noise to the tag that is not very useful to know. 

The git commit that the image was built from should be descriptive enough so that we can easily pin-point the exact version of the `rockraft.yaml` file that was used to build the image.

Edit by @ca-scribner: for background, the current version scheme and justification is defined in [this spec](https://docs.google.com/document/d/1hrq1uhNd4_vjURMH1YIp0s2y54lXJXoAkFsBcsQuY9o/edit)

**Comment by ca-scribner** [comment]
Some open questions we need to close to implement this (they're in no particular order, but numbering them so they're easier to refer to later):

### 1. Will we ever publish the same image in multiple bases at one time?  

Eg, `mlserver-sklearn` on both 22.04 and 22.10.  If yes, how does our github/ci capture this in the proposed naming convention?  I think yes we will hit this sometimes, not because we want to maintain two images generally but because any time we transition from one base to another we probably need a short overlap.  

in the OP's proposal, image `mlserver-sklearn` is named `mlserver-sklearn:1.2.0-HASH` where `HASH` is the rock repo hash at publish time.  so if a publish ever has multiple bases, the versioning scheme breaks.  How can we handle this case?

### 2. Does it matter that `rockcraft.yaml`'s `version` metadata is out of sync with the published version?

the `rockcraft.yaml` file has a required [version](https://canonical-rockcraft.readthedocs-hosted.com/en/latest/reference/rockcraft.yaml/#version) field that is for:

> The ROCK version, used to tag the OCI image and name the ROCK file

If we publish to tags that include HASH, we have a chicken and egg problem - the `rockcraft.yaml` file can never include its own commit hash, because the hash depends on the commit.  This version text does appear in the image (see `RepoTags` field [here](https://pastebin.ubuntu.com/p/TGsxC4665Y/)) - is there a consequence if we tag/push to dockerhub under a different tag?

My guess is there's no real consequence to this being wrong, but we should confirm (asked [here](https://chat.charmhub.io/charmhub/pl/min1bn6jg7f7bpz9d6rfxwxsar)).  If this is really important, we could set `version: PLACEHOLDER` in our rockcraft.yaml files and then during publish time (after the commit hash is known) inject the commit hash into `version`

**Comment by ca-scribner** [comment]
If we do go with `<upstream-version>-<commit-hash>`, I propose we write our `rockfile.yaml` like:

```yaml
name: some-image
version: 1.2.3
...
```

where `1.2.3` is the version of the application being rocked, then our CI injects the commit hash at publish.  If someone packs the rock locally, they'll still have a meaningful tag so their image doesn't get mixed up with others.

**Comment by ca-scribner** [comment]
For background, the current image version scheme was defined in [this spec](https://docs.google.com/document/d/1hrq1uhNd4_vjURMH1YIp0s2y54lXJXoAkFsBcsQuY9o/edit).  Not saying we shouldn't change it because there's a spec, just that it adds context

**Comment by ca-scribner** [comment]
@orfeas-k that is a great point.  If the ingredients that go into these images are mutable, that makes things much less clear.

**Comment by ca-scribner** [comment]
Agreements from an offline discussion:
* we will use `<upstream-version>-<commit>` as proposed
* CI will need to be updated to:
  * [ ] fetch and append the git commit hash to all image uploads (some of our CI does this already)
  * [ ] before uploading, will check if there is an image already published with this tag and fail if that happens (to avoid accidentally mutating images)
* [ ] all rocks repos will need to have their `version:` field changed to just be the software version (eg mlflow's `1.2.0`, etc)
