### ISSUE TITLE
MariaDB to MysqlDB migration peculiarites

### ISSUE THREAD

**Issue by nishant-dash** [canonical/bundle-kubeflow#793]
### Bug Description

For the [db-migrations](https://charmed-kubeflow.io/docs/databases-migration-guide)
This guide assumes that the pod/internal cluster IPs are directly reachable from where the commands are being run. This however won't be the case in most production environments as the operator will be running this from an infra node/jumphost and the only way to reach those IPs is via a kubectl port forward.

I have tried to forward them to the jumphost, but connecting to mysql over this forward fails. Hence I replace all the connection commands with `juju ssh` or `juju exec`. Juju inherently opens a port forward and handles connecting to the unit. 
The db workload pods themselves come bundled with `mysqldump` and other utilities, so I make use of the utilities in the workload container to do the db dumps and just copy it out of the container. 

However, the mysqldump utility I see inside maridb does not have `--column-statistics` whereas the the binary in the mysql charm does have it.

In mariabdb
```console
$ juju ssh --remote kfp-db/0 "mysqldump --version"
mysqldump  Ver 10.17 Distrib 10.3.17-MariaDB, for debian-linux-gnu (x86_64)
```

In mysql
```console
$ juju ssh --container mysql kfp-db-mysql/0 "mysqldump --version"
mysqldump  Ver 8.0.34-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu))
```

### To Reproduce

N/A

### Environment

- KF 1.7/stable but with mariabdb charms for Kfp-DB and Katib-DB
- juju 2.9.43

### Relevant Log Output

```shell
$ juju ssh --remote katib-db/0 mysqldump --user=root --password=root --column-statistics=0 --databases katib
mysqldump: unknown variable 'column-statistics=0'
ERROR command terminated with exit code 7
```

**Comment by DnPlas** [comment]
After a debug session with @nishant-dash we concluded that:

1. The [`--column-statistic` flag](https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_column-statistics):

> Add [ANALYZE TABLE](https://dev.mysql.com/doc/refman/8.0/en/analyze-table.html) statements to the output to generate histogram statistics for dumped tables when the dump file is reloaded

which is something that we can remove from the `mysqldump --host=$DB_IP --user=$DB_USER --password=$DB_PASSWORD --column-statistics=0 --databases katib > katib-db.sql` command that the migration guide suggests if we are not interested in having these statistics.

2. Data is not compromised when running the `mysqldump` command without the `column-statistics` flag.

Using KFP as an example, we successfully migrated the databse from mariadb to mysql with the instructions provided in the guide, but removing the flag. No data was lost in the process.

3. The error message is due to the version of `mysqldump` not supporting this option.

```
mysqldump: unknown variable 'column-statistics=0'
ERROR command terminated with exit code 7
```

Closing this issue, but feel free to re-open if you run into this again.
