### ISSUE TITLE
publish bundle fails with `'.' is not a file`.

### ISSUE THREAD

**Issue by orfeas-k** [canonical/bundle-kubeflow#828]
### Bug Description

Publish bundle for `latest/edge` bundle fails with the following error
```bash
Error: Error running subcommand ``charmcraft upload  --release latest/edge``: `'.' is not a file.
```
Here is the run where this [first occured](https://github.com/canonical/bundle-kubeflow/actions/runs/7933174378/job/21718137185#step:3:23). We hadn't run this since 3 months ago, so it could be that something changed in the action.

This could be an issue with [upload-bundle](https://github.com/canonical/charming-actions/tree/main/upload-bundle) action but more investigation is needed.

### To Reproduce

Merge a PR modifying `latest/edge` bundle.

### Environment

GH runner

### Relevant Log Output

```shell
Run canonical/charming-actions/upload-bundle@1.0.0
  with:
    credentials: ***
    github-token: ***
    bundle-path: ./releases/latest/edge/
    channel: latest/edge
    charmcraft-channel: latest/edge
/usr/bin/sudo snap install charmcraft --classic --channel latest/edge
charmcraft (edge) 2.5.5.post85+g75722ac from Canonical** installed
/usr/bin/sudo snap install juju-bundle --classic
juju-bundle 0.4.0 from Kenneth Koski (kennethkoski) installed
/snap/bin/juju-bundle publish --destructive-mode --serial --release latest/edge
Ensuring valid credentials with `charmcraft whoami`.
name: Michal Huckko
username: michalhucko
id: TdvDVO8EijykLIQGmU3P3FWRaEHfEJUW
permissions:
- account-register-package
- account-view-packages
- package-manage
- package-view
Error: Error running subcommand ``charmcraft upload  --release latest/edge``: `'.' is not a file.
Full execution log: '/home/runner/.local/state/charmcraft/log/charmcraft-20240219-084250.355679.log'
`
Error: The process '/snap/bin/juju-bundle' failed with exit code 1
Error: Error: The process '/snap/bin/juju-bundle' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/canonical/charming-actions/1.0.0/dist/upload-bundle/index.js:2600:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/canonical/charming-actions/1.0.0/dist/upload-bundle/index.js:2583:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/canonical/charming-actions/1.0.0/dist/upload-bundle/index.js:2477:27)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Socket.<anonymous> (node:internal/child_process:458:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:301:12)
No charmcraft logs generated, skipping artifact upload.
```

**Comment by mvlassis** [comment]
To troubleshoot the issue, I tried to trace the order of execution of the Github action. Here's what I have gathered:
-  The issue occurs when triggering the [release-bundle-to-charmhub.yaml](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/release-bundle-to-charmhub.yaml) action.
- That action calls the [run-tests-and-publish-bundle.yaml](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/run-tests-and-publish-bundle.yaml) action.
- This in turn calls the [upload-bundle](https://github.com/canonical/charming-actions/tree/main/upload-bundle) action from the `charming-actions` repo.
- That action invokes an [index.js](https://github.com/canonical/charming-actions/blob/main/dist/upload-bundle/index.js) file, and specifically the [publish function](https://github.com/canonical/charming-actions/blob/main/dist/upload-bundle/index.js#L42714). 
- The function calls the `juju-bundle` executable from the terminal. The executable's `main.rs` is [here](https://github.com/canonical/juju-bundle/blob/master/src/main.rs).
- The [publish subcommand](https://github.com/canonical/juju-bundle/blob/c815950b62f5c86e03980e282e0b13ad28f8978f/src/main.rs#L353) is called, which creates a temporary directory in `/tmp` with a `README.md`, a `bundle.yaml`, and a `charmcraft.yaml`. In the [last line](https://github.com/canonical/juju-bundle/blob/c815950b62f5c86e03980e282e0b13ad28f8978f/src/main.rs#L419) of the function, the `upload_charmhub` function for the Bundle object is called, with the temporary directory  and the specified channel as argument.
- The `upload_charmhub()` function is derived from the `juju-rs` interface for Rust, and specifically [this function](https://github.com/canonical/rust-libjuju/blob/e5d863553a6d758bac25379755ee27852e6aac4b/src/bundle.rs#L298). 
- The function calls `charmcraft pack` from the terminal, as seen [here](https://github.com/canonical/rust-libjuju/blob/e5d863553a6d758bac25379755ee27852e6aac4b/src/bundle.rs#L299), and captures the output. To receive the actual name of the produced `.zip` file, it uses [this iteration chain](https://github.com/canonical/rust-libjuju/blob/e5d863553a6d758bac25379755ee27852e6aac4b/src/bundle.rs#L302). As explained in the commend, it tries to capture the produced file's name by getting everything between the first two single quote characters.

Here lies the issue. Calling `charmcraft pack` returns a message like the following:
```
Packaged kubeflow.zip
```
Because kubeflow.zip is not enclosed with quotes, the first `while` statement iterates through the whole sequence, and thus an empty string is returned. When the function then tries to call `charmcraft upload` [here](https://github.com/canonical/rust-libjuju/blob/e5d863553a6d758bac25379755ee27852e6aac4b/src/bundle.rs#L310), it does with an empty string as a path "". Charmcraft upload reads this as putting "." as an argument and outputs the exact error message described in this issue. You can check this yourself by running `charmcraft upload ""`.

Proposed fix: [this chained iteration](https://github.com/canonical/rust-libjuju/blob/e5d863553a6d758bac25379755ee27852e6aac4b/src/bundle.rs#L302) should be changed to capture the output properly, maybe by getting all output after the first space character " ". I couldn't find more information on where the command output is specified for `charmcraft upload` on the [charmcraft repo](https://github.com/canonical/charmcraft).
